//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.TimestampedObjectType;

public class Adapter9
    extends XmlAdapter<String, TimestampedObjectType>
{


    public TimestampedObjectType unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.TimestampedObjectTypeParser.parse(value));
    }

    public String marshal(TimestampedObjectType value) {
        return (eu.europa.esig.dss.jaxb.parsers.TimestampedObjectTypeParser.print(value));
    }

}
