//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.CertificateOrigin;

public class Adapter13
    extends XmlAdapter<String, CertificateOrigin>
{


    public CertificateOrigin unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.CertificateOriginParser.parse(value));
    }

    public String marshal(CertificateOrigin value) {
        return (eu.europa.esig.dss.jaxb.parsers.CertificateOriginParser.print(value));
    }

}
