//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 12:26:43 PM EET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateExtensions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateExtensions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="KeyUsages" type="{http://dss.esig.europa.eu/validation/diagnostic}KeyUsages"/&gt;
 *           &lt;element name="ExtendedKeyUsages" type="{http://dss.esig.europa.eu/validation/diagnostic}ExtendedKeyUsages"/&gt;
 *           &lt;element name="CertificatePolicies" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificatePolicies"/&gt;
 *           &lt;element name="SubjectAlternativeNames" type="{http://dss.esig.europa.eu/validation/diagnostic}SubjectAlternativeNames"/&gt;
 *           &lt;element name="BasicConstraints" type="{http://dss.esig.europa.eu/validation/diagnostic}BasicConstraints"/&gt;
 *           &lt;element name="PolicyConstraints" type="{http://dss.esig.europa.eu/validation/diagnostic}PolicyConstraints"/&gt;
 *           &lt;element name="InhibitAnyPolicy" type="{http://dss.esig.europa.eu/validation/diagnostic}InhibitAnyPolicy"/&gt;
 *           &lt;element name="NameConstraints" type="{http://dss.esig.europa.eu/validation/diagnostic}NameConstraints"/&gt;
 *           &lt;element name="CRLDistributionPoints" type="{http://dss.esig.europa.eu/validation/diagnostic}CRLDistributionPoints"/&gt;
 *           &lt;element name="AuthorityKeyIdentifier" type="{http://dss.esig.europa.eu/validation/diagnostic}AuthorityKeyIdentifier"/&gt;
 *           &lt;element name="SubjectKeyIdentifier" type="{http://dss.esig.europa.eu/validation/diagnostic}SubjectKeyIdentifier"/&gt;
 *           &lt;element name="AuthorityInformationAccess" type="{http://dss.esig.europa.eu/validation/diagnostic}AuthorityInformationAccess"/&gt;
 *           &lt;element name="IdPkixOcspNoCheck" type="{http://dss.esig.europa.eu/validation/diagnostic}IdPkixOcspNoCheck"/&gt;
 *           &lt;element name="ValAssuredShortTermCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}ValAssuredShortTermCertificate"/&gt;
 *           &lt;element name="QcStatements" type="{http://dss.esig.europa.eu/validation/diagnostic}QcStatements"/&gt;
 *           &lt;element name="OtherExtension" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateExtension"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateExtensions", propOrder = {
    "keyUsagesOrExtendedKeyUsagesOrCertificatePolicies"
})
public class XmlCertificateExtensions
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "KeyUsages", type = XmlKeyUsages.class),
        @XmlElement(name = "ExtendedKeyUsages", type = XmlExtendedKeyUsages.class),
        @XmlElement(name = "CertificatePolicies", type = XmlCertificatePolicies.class),
        @XmlElement(name = "SubjectAlternativeNames", type = XmlSubjectAlternativeNames.class),
        @XmlElement(name = "BasicConstraints", type = XmlBasicConstraints.class),
        @XmlElement(name = "PolicyConstraints", type = XmlPolicyConstraints.class),
        @XmlElement(name = "InhibitAnyPolicy", type = XmlInhibitAnyPolicy.class),
        @XmlElement(name = "NameConstraints", type = XmlNameConstraints.class),
        @XmlElement(name = "CRLDistributionPoints", type = XmlCRLDistributionPoints.class),
        @XmlElement(name = "AuthorityKeyIdentifier", type = XmlAuthorityKeyIdentifier.class),
        @XmlElement(name = "SubjectKeyIdentifier", type = XmlSubjectKeyIdentifier.class),
        @XmlElement(name = "AuthorityInformationAccess", type = XmlAuthorityInformationAccess.class),
        @XmlElement(name = "IdPkixOcspNoCheck", type = XmlIdPkixOcspNoCheck.class),
        @XmlElement(name = "ValAssuredShortTermCertificate", type = XmlValAssuredShortTermCertificate.class),
        @XmlElement(name = "QcStatements", type = XmlQcStatements.class),
        @XmlElement(name = "OtherExtension")
    })
    protected List<XmlCertificateExtension> keyUsagesOrExtendedKeyUsagesOrCertificatePolicies;

    /**
     * Gets the value of the keyUsagesOrExtendedKeyUsagesOrCertificatePolicies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyUsagesOrExtendedKeyUsagesOrCertificatePolicies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyUsagesOrExtendedKeyUsagesOrCertificatePolicies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlAuthorityInformationAccess }
     * {@link XmlAuthorityKeyIdentifier }
     * {@link XmlBasicConstraints }
     * {@link XmlCRLDistributionPoints }
     * {@link XmlCertificateExtension }
     * {@link XmlCertificatePolicies }
     * {@link XmlExtendedKeyUsages }
     * {@link XmlIdPkixOcspNoCheck }
     * {@link XmlInhibitAnyPolicy }
     * {@link XmlKeyUsages }
     * {@link XmlNameConstraints }
     * {@link XmlPolicyConstraints }
     * {@link XmlQcStatements }
     * {@link XmlSubjectAlternativeNames }
     * {@link XmlSubjectKeyIdentifier }
     * {@link XmlValAssuredShortTermCertificate }
     * 
     * 
     */
    public List<XmlCertificateExtension> getKeyUsagesOrExtendedKeyUsagesOrCertificatePolicies() {
        if (keyUsagesOrExtendedKeyUsagesOrCertificatePolicies == null) {
            keyUsagesOrExtendedKeyUsagesOrCertificatePolicies = new ArrayList<XmlCertificateExtension>();
        }
        return this.keyUsagesOrExtendedKeyUsagesOrCertificatePolicies;
    }

}
