//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementWrapper;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.europa.esig.dss.enumerations.EvidenceRecordTypeEnum;


/**
 * <p>Java class for EvidenceRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/diagnostic}AbstractToken"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Type" type="{http://dss.esig.europa.eu/validation/diagnostic}EvidenceRecordType" minOccurs="0"/&gt;
 *         &lt;element name="StructuralValidation" type="{http://dss.esig.europa.eu/validation/diagnostic}StructuralValidation" minOccurs="0"/&gt;
 *         &lt;element name="DigestMatchers" type="{http://dss.esig.europa.eu/validation/diagnostic}DigestMatchers"/&gt;
 *         &lt;element name="EvidenceRecordTimestamps"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="FoundTimestamp" type="{http://dss.esig.europa.eu/validation/diagnostic}FoundTimestamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FoundCertificates" type="{http://dss.esig.europa.eu/validation/diagnostic}FoundCertificates"/&gt;
 *         &lt;element name="FoundRevocations" type="{http://dss.esig.europa.eu/validation/diagnostic}FoundRevocations"/&gt;
 *         &lt;element name="TimestampedObjects" type="{http://dss.esig.europa.eu/validation/diagnostic}TimestampedObjects"/&gt;
 *         &lt;element name="EvidenceRecordScopes"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SignatureScope" type="{http://dss.esig.europa.eu/validation/diagnostic}SignatureScope" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Base64Encoded" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="DigestAlgoAndValue" type="{http://dss.esig.europa.eu/validation/diagnostic}DigestAlgoAndValue"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceRecord", propOrder = {
    "documentName",
    "type",
    "structuralValidation",
    "digestMatchers",
    "evidenceRecordTimestamps",
    "foundCertificates",
    "foundRevocations",
    "timestampedObjects",
    "evidenceRecordScopes",
    "base64Encoded",
    "digestAlgoAndValue"
})
public class XmlEvidenceRecord
    extends XmlAbstractToken
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "DocumentName")
    protected String documentName;
    @XmlElement(name = "Type", type = String.class)
    @XmlJavaTypeAdapter(Adapter23 .class)
    protected EvidenceRecordTypeEnum type;
    @XmlElement(name = "StructuralValidation")
    protected XmlStructuralValidation structuralValidation;
    @XmlElementWrapper(name = "DigestMatchers", required = true)
    @XmlElement(name = "DigestMatcher", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlDigestMatcher> digestMatchers;
    @XmlElementWrapper(name = "EvidenceRecordTimestamps", required = true)
    @XmlElement(name = "FoundTimestamp", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlFoundTimestamp> evidenceRecordTimestamps;
    @XmlElement(name = "FoundCertificates", required = true)
    protected XmlFoundCertificates foundCertificates;
    @XmlElement(name = "FoundRevocations", required = true)
    protected XmlFoundRevocations foundRevocations;
    @XmlElementWrapper(name = "TimestampedObjects", required = true)
    @XmlElement(name = "TimestampedObject", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlTimestampedObject> timestampedObjects;
    @XmlElementWrapper(name = "EvidenceRecordScopes", required = true)
    @XmlElement(name = "SignatureScope", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlSignatureScope> evidenceRecordScopes;
    @XmlElement(name = "Base64Encoded")
    protected byte[] base64Encoded;
    @XmlElement(name = "DigestAlgoAndValue")
    protected XmlDigestAlgoAndValue digestAlgoAndValue;

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public EvidenceRecordTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(EvidenceRecordTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the structuralValidation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlStructuralValidation }
     *     
     */
    public XmlStructuralValidation getStructuralValidation() {
        return structuralValidation;
    }

    /**
     * Sets the value of the structuralValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlStructuralValidation }
     *     
     */
    public void setStructuralValidation(XmlStructuralValidation value) {
        this.structuralValidation = value;
    }

    /**
     * Gets the value of the foundCertificates property.
     * 
     * @return
     *     possible object is
     *     {@link XmlFoundCertificates }
     *     
     */
    public XmlFoundCertificates getFoundCertificates() {
        return foundCertificates;
    }

    /**
     * Sets the value of the foundCertificates property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlFoundCertificates }
     *     
     */
    public void setFoundCertificates(XmlFoundCertificates value) {
        this.foundCertificates = value;
    }

    /**
     * Gets the value of the foundRevocations property.
     * 
     * @return
     *     possible object is
     *     {@link XmlFoundRevocations }
     *     
     */
    public XmlFoundRevocations getFoundRevocations() {
        return foundRevocations;
    }

    /**
     * Sets the value of the foundRevocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlFoundRevocations }
     *     
     */
    public void setFoundRevocations(XmlFoundRevocations value) {
        this.foundRevocations = value;
    }

    /**
     * Gets the value of the base64Encoded property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBase64Encoded() {
        return base64Encoded;
    }

    /**
     * Sets the value of the base64Encoded property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBase64Encoded(byte[] value) {
        this.base64Encoded = value;
    }

    /**
     * Gets the value of the digestAlgoAndValue property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDigestAlgoAndValue }
     *     
     */
    public XmlDigestAlgoAndValue getDigestAlgoAndValue() {
        return digestAlgoAndValue;
    }

    /**
     * Sets the value of the digestAlgoAndValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDigestAlgoAndValue }
     *     
     */
    public void setDigestAlgoAndValue(XmlDigestAlgoAndValue value) {
        this.digestAlgoAndValue = value;
    }

    public List<XmlDigestMatcher> getDigestMatchers() {
        if (digestMatchers == null) {
            digestMatchers = new ArrayList<XmlDigestMatcher>();
        }
        return digestMatchers;
    }

    public void setDigestMatchers(List<XmlDigestMatcher> digestMatchers) {
        this.digestMatchers = digestMatchers;
    }

    public List<XmlFoundTimestamp> getEvidenceRecordTimestamps() {
        if (evidenceRecordTimestamps == null) {
            evidenceRecordTimestamps = new ArrayList<XmlFoundTimestamp>();
        }
        return evidenceRecordTimestamps;
    }

    public void setEvidenceRecordTimestamps(List<XmlFoundTimestamp> evidenceRecordTimestamps) {
        this.evidenceRecordTimestamps = evidenceRecordTimestamps;
    }

    public List<XmlTimestampedObject> getTimestampedObjects() {
        if (timestampedObjects == null) {
            timestampedObjects = new ArrayList<XmlTimestampedObject>();
        }
        return timestampedObjects;
    }

    public void setTimestampedObjects(List<XmlTimestampedObject> timestampedObjects) {
        this.timestampedObjects = timestampedObjects;
    }

    public List<XmlSignatureScope> getEvidenceRecordScopes() {
        if (evidenceRecordScopes == null) {
            evidenceRecordScopes = new ArrayList<XmlSignatureScope>();
        }
        return evidenceRecordScopes;
    }

    public void setEvidenceRecordScopes(List<XmlSignatureScope> evidenceRecordScopes) {
        this.evidenceRecordScopes = evidenceRecordScopes;
    }

}
