//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FoundEvidenceRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FoundEvidenceRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="EvidenceRecord" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FoundEvidenceRecord")
public class XmlFoundEvidenceRecord implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlAttribute(name = "EvidenceRecord", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected XmlEvidenceRecord evidenceRecord;

    /**
     * Gets the value of the evidenceRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public XmlEvidenceRecord getEvidenceRecord() {
        return evidenceRecord;
    }

    /**
     * Sets the value of the evidenceRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEvidenceRecord(XmlEvidenceRecord value) {
        this.evidenceRecord = value;
    }

}
