//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MRACertificateMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MRACertificateMapping"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TrustServiceEquivalenceInformation" type="{http://dss.esig.europa.eu/validation/diagnostic}TrustServiceEquivalenceInformation"/&gt;
 *         &lt;element name="OriginalThirdCountryMapping" type="{http://dss.esig.europa.eu/validation/diagnostic}OriginalThirdCountryQcStatementsMapping"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MRACertificateMapping", propOrder = {
    "trustServiceEquivalenceInformation",
    "originalThirdCountryMapping"
})
public class XmlMRACertificateMapping implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "TrustServiceEquivalenceInformation", required = true)
    protected XmlTrustServiceEquivalenceInformation trustServiceEquivalenceInformation;
    @XmlElement(name = "OriginalThirdCountryMapping", required = true)
    protected XmlOriginalThirdCountryQcStatementsMapping originalThirdCountryMapping;

    /**
     * Gets the value of the trustServiceEquivalenceInformation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTrustServiceEquivalenceInformation }
     *     
     */
    public XmlTrustServiceEquivalenceInformation getTrustServiceEquivalenceInformation() {
        return trustServiceEquivalenceInformation;
    }

    /**
     * Sets the value of the trustServiceEquivalenceInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTrustServiceEquivalenceInformation }
     *     
     */
    public void setTrustServiceEquivalenceInformation(XmlTrustServiceEquivalenceInformation value) {
        this.trustServiceEquivalenceInformation = value;
    }

    /**
     * Gets the value of the originalThirdCountryMapping property.
     * 
     * @return
     *     possible object is
     *     {@link XmlOriginalThirdCountryQcStatementsMapping }
     *     
     */
    public XmlOriginalThirdCountryQcStatementsMapping getOriginalThirdCountryMapping() {
        return originalThirdCountryMapping;
    }

    /**
     * Sets the value of the originalThirdCountryMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlOriginalThirdCountryQcStatementsMapping }
     *     
     */
    public void setOriginalThirdCountryMapping(XmlOriginalThirdCountryQcStatementsMapping value) {
        this.originalThirdCountryMapping = value;
    }

}
