//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:11 AM CET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementWrapper;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrustServiceEquivalenceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrustServiceEquivalenceInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TrustServiceLegalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CertificateContentEquivalenceList" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateContentEquivalenceList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrustServiceEquivalenceInformation", propOrder = {
    "trustServiceLegalIdentifier",
    "certificateContentEquivalenceList"
})
public class XmlTrustServiceEquivalenceInformation implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "TrustServiceLegalIdentifier", required = true)
    protected String trustServiceLegalIdentifier;
    @XmlElementWrapper(name = "CertificateContentEquivalenceList")
    @XmlElement(name = "CertificateContentEquivalence", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlCertificateContentEquivalence> certificateContentEquivalenceList;

    /**
     * Gets the value of the trustServiceLegalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrustServiceLegalIdentifier() {
        return trustServiceLegalIdentifier;
    }

    /**
     * Sets the value of the trustServiceLegalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrustServiceLegalIdentifier(String value) {
        this.trustServiceLegalIdentifier = value;
    }

    public List<XmlCertificateContentEquivalence> getCertificateContentEquivalenceList() {
        if (certificateContentEquivalenceList == null) {
            certificateContentEquivalenceList = new ArrayList<XmlCertificateContentEquivalence>();
        }
        return certificateContentEquivalenceList;
    }

    public void setCertificateContentEquivalenceList(List<XmlCertificateContentEquivalence> certificateContentEquivalenceList) {
        this.certificateContentEquivalenceList = certificateContentEquivalenceList;
    }

}
