//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.TimestampQualification;

public class Adapter6
    extends XmlAdapter<String, TimestampQualification>
{


    public TimestampQualification unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.TimestampQualificationParser.parse(value));
    }

    public String marshal(TimestampQualification value) {
        return (eu.europa.esig.dss.jaxb.parsers.TimestampQualificationParser.print(value));
    }

}
