//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlockType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="BlockType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SIG_BBB"/&gt;
 *     &lt;enumeration value="REV_BBB"/&gt;
 *     &lt;enumeration value="TST_BBB"/&gt;
 *     &lt;enumeration value="CNT_TST_BBB"/&gt;
 *     &lt;enumeration value="CRS"/&gt;
 *     &lt;enumeration value="PSV_CRS"/&gt;
 *     &lt;enumeration value="RAC"/&gt;
 *     &lt;enumeration value="RFC"/&gt;
 *     &lt;enumeration value="SUB_XCV"/&gt;
 *     &lt;enumeration value="REV_CC"/&gt;
 *     &lt;enumeration value="ER"/&gt;
 *     &lt;enumeration value="PSV"/&gt;
 *     &lt;enumeration value="PCV"/&gt;
 *     &lt;enumeration value="VTS"/&gt;
 *     &lt;enumeration value="TST_PSV"/&gt;
 *     &lt;enumeration value="TST"/&gt;
 *     &lt;enumeration value="ER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "BlockType")
@XmlEnum
public enum XmlBlockType {

    SIG_BBB,
    REV_BBB,
    TST_BBB,
    CNT_TST_BBB,
    CRS,
    PSV_CRS,
    RAC,
    RFC,
    SUB_XCV,
    REV_CC,
    ER,
    PSV,
    PCV,
    VTS,
    TST_PSV,
    TST;

    public String value() {
        return name();
    }

    public static XmlBlockType fromValue(String v) {
        return valueOf(v);
    }

}
