//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import java.io.Serializable;
import java.util.Date;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CC"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/detailed-report}ConstraintsConclusion"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VerifiedAlgorithm" type="{http://dss.esig.europa.eu/validation/detailed-report}CryptographicAlgorithm"/&gt;
 *         &lt;element name="NotAfter" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CC", propOrder = {
    "verifiedAlgorithm",
    "notAfter"
})
public class XmlCC
    extends XmlConstraintsConclusion
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "VerifiedAlgorithm", required = true)
    protected XmlCryptographicAlgorithm verifiedAlgorithm;
    @XmlElement(name = "NotAfter", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date notAfter;

    /**
     * Gets the value of the verifiedAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCryptographicAlgorithm }
     *     
     */
    public XmlCryptographicAlgorithm getVerifiedAlgorithm() {
        return verifiedAlgorithm;
    }

    /**
     * Sets the value of the verifiedAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCryptographicAlgorithm }
     *     
     */
    public void setVerifiedAlgorithm(XmlCryptographicAlgorithm value) {
        this.verifiedAlgorithm = value;
    }

    /**
     * Gets the value of the notAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getNotAfter() {
        return notAfter;
    }

    /**
     * Sets the value of the notAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotAfter(Date value) {
        this.notAfter = value;
    }

}
