//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvidenceRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValidationProcessEvidenceRecord" type="{http://dss.esig.europa.eu/validation/detailed-report}ValidationProcessEvidenceRecord"/&gt;
 *         &lt;element name="Timestamp" type="{http://dss.esig.europa.eu/validation/detailed-report}Timestamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Conclusion" type="{http://dss.esig.europa.eu/validation/detailed-report}Conclusion"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceRecord", propOrder = {
    "validationProcessEvidenceRecord",
    "timestamps",
    "conclusion"
})
public class XmlEvidenceRecord implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "ValidationProcessEvidenceRecord", required = true)
    protected XmlValidationProcessEvidenceRecord validationProcessEvidenceRecord;
    @XmlElement(name = "Timestamp")
    protected List<XmlTimestamp> timestamps;
    @XmlElement(name = "Conclusion", required = true)
    protected XmlConclusion conclusion;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the validationProcessEvidenceRecord property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValidationProcessEvidenceRecord }
     *     
     */
    public XmlValidationProcessEvidenceRecord getValidationProcessEvidenceRecord() {
        return validationProcessEvidenceRecord;
    }

    /**
     * Sets the value of the validationProcessEvidenceRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValidationProcessEvidenceRecord }
     *     
     */
    public void setValidationProcessEvidenceRecord(XmlValidationProcessEvidenceRecord value) {
        this.validationProcessEvidenceRecord = value;
    }

    /**
     * Gets the value of the timestamps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timestamps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimestamps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlTimestamp }
     * 
     * 
     */
    public List<XmlTimestamp> getTimestamps() {
        if (timestamps == null) {
            timestamps = new ArrayList<XmlTimestamp>();
        }
        return this.timestamps;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link XmlConclusion }
     *     
     */
    public XmlConclusion getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlConclusion }
     *     
     */
    public void setConclusion(XmlConclusion value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
