//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SAV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAV"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/detailed-report}ConstraintsConclusion"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CryptographicValidation" type="{http://dss.esig.europa.eu/validation/detailed-report}CryptographicValidation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAV", propOrder = {
    "cryptographicValidation"
})
public class XmlSAV
    extends XmlConstraintsConclusion
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "CryptographicValidation", required = true)
    protected XmlCryptographicValidation cryptographicValidation;

    /**
     * Gets the value of the cryptographicValidation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCryptographicValidation }
     *     
     */
    public XmlCryptographicValidation getCryptographicValidation() {
        return cryptographicValidation;
    }

    /**
     * Sets the value of the cryptographicValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCryptographicValidation }
     *     
     */
    public void setCryptographicValidation(XmlCryptographicValidation value) {
        this.cryptographicValidation = value;
    }

}
