//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Timestamp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Timestamp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValidationProcessBasicTimestamp" type="{http://dss.esig.europa.eu/validation/detailed-report}ValidationProcessBasicTimestamp"/&gt;
 *         &lt;element name="ValidationProcessArchivalDataTimestamp" type="{http://dss.esig.europa.eu/validation/detailed-report}ValidationProcessArchivalDataTimestamp" minOccurs="0"/&gt;
 *         &lt;element name="ValidationTimestampQualification" type="{http://dss.esig.europa.eu/validation/detailed-report}ValidationTimestampQualification" minOccurs="0"/&gt;
 *         &lt;element name="Conclusion" type="{http://dss.esig.europa.eu/validation/detailed-report}Conclusion"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Timestamp", propOrder = {
    "validationProcessBasicTimestamp",
    "validationProcessArchivalDataTimestamp",
    "validationTimestampQualification",
    "conclusion"
})
public class XmlTimestamp implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "ValidationProcessBasicTimestamp", required = true)
    protected XmlValidationProcessBasicTimestamp validationProcessBasicTimestamp;
    @XmlElement(name = "ValidationProcessArchivalDataTimestamp")
    protected XmlValidationProcessArchivalDataTimestamp validationProcessArchivalDataTimestamp;
    @XmlElement(name = "ValidationTimestampQualification")
    protected XmlValidationTimestampQualification validationTimestampQualification;
    @XmlElement(name = "Conclusion", required = true)
    protected XmlConclusion conclusion;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the validationProcessBasicTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValidationProcessBasicTimestamp }
     *     
     */
    public XmlValidationProcessBasicTimestamp getValidationProcessBasicTimestamp() {
        return validationProcessBasicTimestamp;
    }

    /**
     * Sets the value of the validationProcessBasicTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValidationProcessBasicTimestamp }
     *     
     */
    public void setValidationProcessBasicTimestamp(XmlValidationProcessBasicTimestamp value) {
        this.validationProcessBasicTimestamp = value;
    }

    /**
     * Gets the value of the validationProcessArchivalDataTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValidationProcessArchivalDataTimestamp }
     *     
     */
    public XmlValidationProcessArchivalDataTimestamp getValidationProcessArchivalDataTimestamp() {
        return validationProcessArchivalDataTimestamp;
    }

    /**
     * Sets the value of the validationProcessArchivalDataTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValidationProcessArchivalDataTimestamp }
     *     
     */
    public void setValidationProcessArchivalDataTimestamp(XmlValidationProcessArchivalDataTimestamp value) {
        this.validationProcessArchivalDataTimestamp = value;
    }

    /**
     * Gets the value of the validationTimestampQualification property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValidationTimestampQualification }
     *     
     */
    public XmlValidationTimestampQualification getValidationTimestampQualification() {
        return validationTimestampQualification;
    }

    /**
     * Sets the value of the validationTimestampQualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValidationTimestampQualification }
     *     
     */
    public void setValidationTimestampQualification(XmlValidationTimestampQualification value) {
        this.validationTimestampQualification = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link XmlConclusion }
     *     
     */
    public XmlConclusion getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlConclusion }
     *     
     */
    public void setConclusion(XmlConclusion value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
