//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:22 AM CET 
//


package eu.europa.esig.dss.detailedreport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.europa.esig.dss.enumerations.TimestampQualification;


/**
 * <p>Java class for ValidationTimestampQualification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationTimestampQualification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/detailed-report}ConstraintsConclusion"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValidationTimestampQualificationAtTime" type="{http://dss.esig.europa.eu/validation/detailed-report}ValidationTimestampQualificationAtTime" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="TimestampQualification" use="required" type="{http://dss.esig.europa.eu/validation/detailed-report}TimestampQualification" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationTimestampQualification", propOrder = {
    "validationTimestampQualificationAtTime"
})
public class XmlValidationTimestampQualification
    extends XmlConstraintsConclusion
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "ValidationTimestampQualificationAtTime")
    protected List<XmlValidationTimestampQualificationAtTime> validationTimestampQualificationAtTime;
    @XmlAttribute(name = "TimestampQualification", required = true)
    @XmlJavaTypeAdapter(Adapter6 .class)
    protected TimestampQualification timestampQualification;

    /**
     * Gets the value of the validationTimestampQualificationAtTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validationTimestampQualificationAtTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidationTimestampQualificationAtTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlValidationTimestampQualificationAtTime }
     * 
     * 
     */
    public List<XmlValidationTimestampQualificationAtTime> getValidationTimestampQualificationAtTime() {
        if (validationTimestampQualificationAtTime == null) {
            validationTimestampQualificationAtTime = new ArrayList<XmlValidationTimestampQualificationAtTime>();
        }
        return this.validationTimestampQualificationAtTime;
    }

    /**
     * Gets the value of the timestampQualification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public TimestampQualification getTimestampQualification() {
        return timestampQualification;
    }

    /**
     * Sets the value of the timestampQualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestampQualification(TimestampQualification value) {
        this.timestampQualification = value;
    }

}
