//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.validationreport.enums.TypeOfProof;

public class Adapter2
    extends XmlAdapter<String, TypeOfProof>
{


    public TypeOfProof unmarshal(String value) {
        return (eu.europa.esig.validationreport.parsers.UriBasedEnumParser.parseTypeOfProof(value));
    }

    public String marshal(TypeOfProof value) {
        return (eu.europa.esig.validationreport.parsers.UriBasedEnumParser.print(value));
    }

}
