//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AttributeObject" type="{http://uri.etsi.org/19102/v1.4.1#}VOReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Signed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeBaseType", propOrder = {
    "attributeObject"
})
@XmlSeeAlso({
    SASigningTimeType.class,
    SACertIDListType.class,
    SADataObjectFormatType.class,
    SACommitmentTypeIndicationType.class,
    SASigPolicyIdentifierType.class,
    SASignatureProductionPlaceType.class,
    SASignerRoleType.class,
    SACounterSignatureType.class,
    SARevIDListType.class,
    SADSSType.class,
    SAVRIType.class,
    SAReasonType.class,
    SANameType.class,
    SAContactInfoType.class,
    SASubFilterType.class,
    SATimestampType.class,
    SAMessageDigestType.class
})
public class AttributeBaseType implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "AttributeObject")
    protected List<VOReferenceType> attributeObject;
    @XmlAttribute(name = "Signed")
    protected Boolean signed;

    /**
     * Gets the value of the attributeObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VOReferenceType }
     * 
     * 
     */
    public List<VOReferenceType> getAttributeObject() {
        if (attributeObject == null) {
            attributeObject = new ArrayList<VOReferenceType>();
        }
        return this.attributeObject;
    }

    /**
     * Gets the value of the signed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSigned() {
        return signed;
    }

    /**
     * Sets the value of the signed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSigned(Boolean value) {
        this.signed = value;
    }

}
