//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateChainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateChainType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SigningCertificate" type="{http://uri.etsi.org/19102/v1.4.1#}VOReferenceType"/&gt;
 *         &lt;element name="IntermediateCertificate" type="{http://uri.etsi.org/19102/v1.4.1#}VOReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TrustAnchor" type="{http://uri.etsi.org/19102/v1.4.1#}VOReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="OtherInformation" type="{http://uri.etsi.org/19102/v1.4.1#}AnyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateChainType", propOrder = {
    "signingCertificate",
    "intermediateCertificate",
    "trustAnchor",
    "otherInformation"
})
public class CertificateChainType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "SigningCertificate", required = true)
    protected VOReferenceType signingCertificate;
    @XmlElement(name = "IntermediateCertificate")
    protected List<VOReferenceType> intermediateCertificate;
    @XmlElement(name = "TrustAnchor")
    protected VOReferenceType trustAnchor;
    @XmlElement(name = "OtherInformation")
    protected AnyType otherInformation;

    /**
     * Gets the value of the signingCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link VOReferenceType }
     *     
     */
    public VOReferenceType getSigningCertificate() {
        return signingCertificate;
    }

    /**
     * Sets the value of the signingCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VOReferenceType }
     *     
     */
    public void setSigningCertificate(VOReferenceType value) {
        this.signingCertificate = value;
    }

    /**
     * Gets the value of the intermediateCertificate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intermediateCertificate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntermediateCertificate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VOReferenceType }
     * 
     * 
     */
    public List<VOReferenceType> getIntermediateCertificate() {
        if (intermediateCertificate == null) {
            intermediateCertificate = new ArrayList<VOReferenceType>();
        }
        return this.intermediateCertificate;
    }

    /**
     * Gets the value of the trustAnchor property.
     * 
     * @return
     *     possible object is
     *     {@link VOReferenceType }
     *     
     */
    public VOReferenceType getTrustAnchor() {
        return trustAnchor;
    }

    /**
     * Sets the value of the trustAnchor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VOReferenceType }
     *     
     */
    public void setTrustAnchor(VOReferenceType value) {
        this.trustAnchor = value;
    }

    /**
     * Gets the value of the otherInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOtherInformation() {
        return otherInformation;
    }

    /**
     * Sets the value of the otherInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setOtherInformation(AnyType value) {
        this.otherInformation = value;
    }

}
