//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/19102/v1.4.1#", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.europa.esig.validationreport.jaxb;
