//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SACounterSignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SACounterSignatureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CounterSignature" type="{http://uri.etsi.org/19102/v1.4.1#}SignatureReferenceType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SACounterSignatureType", propOrder = {
    "counterSignature"
})
public class SACounterSignatureType
    extends AttributeBaseType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "CounterSignature", required = true)
    protected SignatureReferenceType counterSignature;

    /**
     * Gets the value of the counterSignature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureReferenceType }
     *     
     */
    public SignatureReferenceType getCounterSignature() {
        return counterSignature;
    }

    /**
     * Sets the value of the counterSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureReferenceType }
     *     
     */
    public void setCounterSignature(SignatureReferenceType value) {
        this.counterSignature = value;
    }

}
