//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SASigPolicyIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SASigPolicyIdentifierType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SigPolicyId" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SASigPolicyIdentifierType", propOrder = {
    "sigPolicyId"
})
public class SASigPolicyIdentifierType
    extends AttributeBaseType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "SigPolicyId", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String sigPolicyId;

    /**
     * Gets the value of the sigPolicyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigPolicyId() {
        return sigPolicyId;
    }

    /**
     * Sets the value of the sigPolicyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigPolicyId(String value) {
        this.sigPolicyId = value;
    }

}
