//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureAttributesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="SigningTime" type="{http://uri.etsi.org/19102/v1.4.1#}SASigningTimeType"/&gt;
 *         &lt;element name="SigningCertificate" type="{http://uri.etsi.org/19102/v1.4.1#}SACertIDListType"/&gt;
 *         &lt;element name="DataObjectFormat" type="{http://uri.etsi.org/19102/v1.4.1#}SADataObjectFormatType"/&gt;
 *         &lt;element name="CommitmentTypeIndication" type="{http://uri.etsi.org/19102/v1.4.1#}SACommitmentTypeIndicationType"/&gt;
 *         &lt;element name="AllDataObjectsTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="IndividualDataObjectsTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="SigPolicyIdentifier" type="{http://uri.etsi.org/19102/v1.4.1#}SASigPolicyIdentifierType"/&gt;
 *         &lt;element name="SignatureProductionPlace" type="{http://uri.etsi.org/19102/v1.4.1#}SASignatureProductionPlaceType"/&gt;
 *         &lt;element name="SignerRole" type="{http://uri.etsi.org/19102/v1.4.1#}SASignerRoleType"/&gt;
 *         &lt;element name="CounterSignature" type="{http://uri.etsi.org/19102/v1.4.1#}SACounterSignatureType"/&gt;
 *         &lt;element name="SignatureTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="CompleteCertificateRefs" type="{http://uri.etsi.org/19102/v1.4.1#}SACertIDListType"/&gt;
 *         &lt;element name="CompleteRevocationRefs" type="{http://uri.etsi.org/19102/v1.4.1#}SARevIDListType"/&gt;
 *         &lt;element name="AttributeCertificateRefs" type="{http://uri.etsi.org/19102/v1.4.1#}SACertIDListType"/&gt;
 *         &lt;element name="AttributeRevocationRefs" type="{http://uri.etsi.org/19102/v1.4.1#}SARevIDListType"/&gt;
 *         &lt;element name="SigAndRefsTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="RefsOnlyTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="CertificateValues" type="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"/&gt;
 *         &lt;element name="RevocationValues" type="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"/&gt;
 *         &lt;element name="AttrAuthoritiesCertValues" type="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"/&gt;
 *         &lt;element name="AttributeRevocationValues" type="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"/&gt;
 *         &lt;element name="TimeStampValidationData" type="{http://uri.etsi.org/19102/v1.4.1#}AttributeBaseType"/&gt;
 *         &lt;element name="ArchiveTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="RenewedDigests" type="{http://uri.etsi.org/19102/v1.4.1#}SAListOfIntegersType"/&gt;
 *         &lt;element name="MessageDigest" type="{http://uri.etsi.org/19102/v1.4.1#}SAMessageDigestType"/&gt;
 *         &lt;element name="DSS" type="{http://uri.etsi.org/19102/v1.4.1#}SADSSType"/&gt;
 *         &lt;element name="VRI" type="{http://uri.etsi.org/19102/v1.4.1#}SAVRIType"/&gt;
 *         &lt;element name="DocTimeStamp" type="{http://uri.etsi.org/19102/v1.4.1#}SATimestampType"/&gt;
 *         &lt;element name="Reason" type="{http://uri.etsi.org/19102/v1.4.1#}SAReasonType"/&gt;
 *         &lt;element name="Name" type="{http://uri.etsi.org/19102/v1.4.1#}SANameType"/&gt;
 *         &lt;element name="ContactInfo" type="{http://uri.etsi.org/19102/v1.4.1#}SAContactInfoType"/&gt;
 *         &lt;element name="SubFilter" type="{http://uri.etsi.org/19102/v1.4.1#}SASubFilterType"/&gt;
 *         &lt;element name="ByteRange" type="{http://uri.etsi.org/19102/v1.4.1#}SAListOfIntegersType"/&gt;
 *         &lt;element name="Filter" type="{http://uri.etsi.org/19102/v1.4.1#}SAFilterType"/&gt;
 *         &lt;element name="OtherInformation" type="{http://uri.etsi.org/19102/v1.4.1#}AnyType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureAttributesType", propOrder = {
    "signingTimeOrSigningCertificateOrDataObjectFormat"
})
public class SignatureAttributesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "SigningTime", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SigningCertificate", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataObjectFormat", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CommitmentTypeIndication", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AllDataObjectsTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IndividualDataObjectsTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SigPolicyIdentifier", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SignatureProductionPlace", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SignerRole", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CounterSignature", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SignatureTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CompleteCertificateRefs", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CompleteRevocationRefs", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AttributeCertificateRefs", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AttributeRevocationRefs", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SigAndRefsTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RefsOnlyTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CertificateValues", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RevocationValues", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AttrAuthoritiesCertValues", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AttributeRevocationValues", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TimeStampValidationData", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ArchiveTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "RenewedDigests", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MessageDigest", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DSS", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "VRI", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DocTimeStamp", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Reason", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Name", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ContactInfo", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SubFilter", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ByteRange", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Filter", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OtherInformation", namespace = "http://uri.etsi.org/19102/v1.4.1#", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> signingTimeOrSigningCertificateOrDataObjectFormat;

    /**
     * Gets the value of the signingTimeOrSigningCertificateOrDataObjectFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signingTimeOrSigningCertificateOrDataObjectFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSigningTimeOrSigningCertificateOrDataObjectFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AnyType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link AttributeBaseType }{@code >}
     * {@link JAXBElement }{@code <}{@link SACertIDListType }{@code >}
     * {@link JAXBElement }{@code <}{@link SACertIDListType }{@code >}
     * {@link JAXBElement }{@code <}{@link SACertIDListType }{@code >}
     * {@link JAXBElement }{@code <}{@link SACommitmentTypeIndicationType }{@code >}
     * {@link JAXBElement }{@code <}{@link SAContactInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link SACounterSignatureType }{@code >}
     * {@link JAXBElement }{@code <}{@link SADSSType }{@code >}
     * {@link JAXBElement }{@code <}{@link SADataObjectFormatType }{@code >}
     * {@link JAXBElement }{@code <}{@link SAFilterType }{@code >}
     * {@link JAXBElement }{@code <}{@link SAMessageDigestType }{@code >}
     * {@link JAXBElement }{@code <}{@link SANameType }{@code >}
     * {@link JAXBElement }{@code <}{@link SAReasonType }{@code >}
     * {@link JAXBElement }{@code <}{@link SARevIDListType }{@code >}
     * {@link JAXBElement }{@code <}{@link SARevIDListType }{@code >}
     * {@link JAXBElement }{@code <}{@link SASigPolicyIdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link SASignatureProductionPlaceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SASignerRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link SASigningTimeType }{@code >}
     * {@link JAXBElement }{@code <}{@link SASubFilterType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SATimestampType }{@code >}
     * {@link JAXBElement }{@code <}{@link SAVRIType }{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getSigningTimeOrSigningCertificateOrDataObjectFormat() {
        if (signingTimeOrSigningCertificateOrDataObjectFormat == null) {
            signingTimeOrSigningCertificateOrDataObjectFormat = new ArrayList<JAXBElement<?>>();
        }
        return this.signingTimeOrSigningCertificateOrDataObjectFormat;
    }

}
