//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:55:27 AM CET 
//


package eu.europa.esig.validationreport.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="CanonicalizationMethod" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *           &lt;element name="DigestMethod" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *           &lt;element name="DigestValue" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{http://uri.etsi.org/19102/v1.4.1#}XAdESSignaturePtr"/&gt;
 *         &lt;element name="PAdESFieldName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OtherInformation" type="{http://uri.etsi.org/19102/v1.4.1#}AnyType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureReferenceType", propOrder = {
    "canonicalizationMethod",
    "digestMethod",
    "digestValue",
    "xAdESSignaturePtr",
    "pAdESFieldName",
    "otherInformation"
})
public class SignatureReferenceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "CanonicalizationMethod")
    @XmlSchemaType(name = "anyURI")
    protected String canonicalizationMethod;
    @XmlElement(name = "DigestMethod")
    @XmlSchemaType(name = "anyURI")
    protected String digestMethod;
    @XmlElement(name = "DigestValue")
    protected byte[] digestValue;
    @XmlElement(name = "XAdESSignaturePtr")
    protected XAdESSignaturePtrType xAdESSignaturePtr;
    @XmlElement(name = "PAdESFieldName")
    protected String pAdESFieldName;
    @XmlElement(name = "OtherInformation")
    protected AnyType otherInformation;

    /**
     * Gets the value of the canonicalizationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanonicalizationMethod() {
        return canonicalizationMethod;
    }

    /**
     * Sets the value of the canonicalizationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanonicalizationMethod(String value) {
        this.canonicalizationMethod = value;
    }

    /**
     * Gets the value of the digestMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestMethod() {
        return digestMethod;
    }

    /**
     * Sets the value of the digestMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestMethod(String value) {
        this.digestMethod = value;
    }

    /**
     * Gets the value of the digestValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDigestValue() {
        return digestValue;
    }

    /**
     * Sets the value of the digestValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDigestValue(byte[] value) {
        this.digestValue = value;
    }

    /**
     * Gets the value of the xAdESSignaturePtr property.
     * 
     * @return
     *     possible object is
     *     {@link XAdESSignaturePtrType }
     *     
     */
    public XAdESSignaturePtrType getXAdESSignaturePtr() {
        return xAdESSignaturePtr;
    }

    /**
     * Sets the value of the xAdESSignaturePtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XAdESSignaturePtrType }
     *     
     */
    public void setXAdESSignaturePtr(XAdESSignaturePtrType value) {
        this.xAdESSignaturePtr = value;
    }

    /**
     * Gets the value of the pAdESFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAdESFieldName() {
        return pAdESFieldName;
    }

    /**
     * Sets the value of the pAdESFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAdESFieldName(String value) {
        this.pAdESFieldName = value;
    }

    /**
     * Gets the value of the otherInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOtherInformation() {
        return otherInformation;
    }

    /**
     * Sets the value of the otherInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setOtherInformation(AnyType value) {
        this.otherInformation = value;
    }

}
