//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:29 AM CET 
//


package eu.europa.esig.dss.simplereport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EvidenceRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/simple-report}Token"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="POETime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="EvidenceRecordScope" type="{http://dss.esig.europa.eu/validation/simple-report}SignatureScope" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Timestamps" type="{http://dss.esig.europa.eu/validation/simple-report}Timestamps" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceRecord", propOrder = {
    "poeTime",
    "evidenceRecordScope",
    "timestamps"
})
public class XmlEvidenceRecord
    extends XmlToken
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "POETime", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date poeTime;
    @XmlElement(name = "EvidenceRecordScope")
    protected List<XmlSignatureScope> evidenceRecordScope;
    @XmlElement(name = "Timestamps")
    protected XmlTimestamps timestamps;

    /**
     * Gets the value of the poeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPOETime() {
        return poeTime;
    }

    /**
     * Sets the value of the poeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOETime(Date value) {
        this.poeTime = value;
    }

    /**
     * Gets the value of the evidenceRecordScope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidenceRecordScope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidenceRecordScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlSignatureScope }
     * 
     * 
     */
    public List<XmlSignatureScope> getEvidenceRecordScope() {
        if (evidenceRecordScope == null) {
            evidenceRecordScope = new ArrayList<XmlSignatureScope>();
        }
        return this.evidenceRecordScope;
    }

    /**
     * Gets the value of the timestamps property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTimestamps }
     *     
     */
    public XmlTimestamps getTimestamps() {
        return timestamps;
    }

    /**
     * Sets the value of the timestamps property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTimestamps }
     *     
     */
    public void setTimestamps(XmlTimestamps value) {
        this.timestamps = value;
    }

}
