//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:04 AM CET 
//


package eu.europa.esig.dss.policy.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Group of constraints on the evidence record
 * 
 * <p>Java class for EvidenceRecordConstraints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceRecordConstraints"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://dss.esig.europa.eu/validation/policy}LevelConstraint"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EvidenceRecordValid" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="DataObjectExistence" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="DataObjectIntact" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="DataObjectFound" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="DataObjectGroup" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="Cryptographic" type="{http://dss.esig.europa.eu/validation/policy}CryptographicConstraint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceRecordConstraints", propOrder = {
    "evidenceRecordValid",
    "dataObjectExistence",
    "dataObjectIntact",
    "dataObjectFound",
    "dataObjectGroup",
    "cryptographic"
})
public class EvidenceRecordConstraints
    extends LevelConstraint
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "EvidenceRecordValid")
    protected LevelConstraint evidenceRecordValid;
    @XmlElement(name = "DataObjectExistence")
    protected LevelConstraint dataObjectExistence;
    @XmlElement(name = "DataObjectIntact")
    protected LevelConstraint dataObjectIntact;
    @XmlElement(name = "DataObjectFound")
    protected LevelConstraint dataObjectFound;
    @XmlElement(name = "DataObjectGroup")
    protected LevelConstraint dataObjectGroup;
    @XmlElement(name = "Cryptographic")
    protected CryptographicConstraint cryptographic;

    /**
     * Gets the value of the evidenceRecordValid property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getEvidenceRecordValid() {
        return evidenceRecordValid;
    }

    /**
     * Sets the value of the evidenceRecordValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setEvidenceRecordValid(LevelConstraint value) {
        this.evidenceRecordValid = value;
    }

    /**
     * Gets the value of the dataObjectExistence property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getDataObjectExistence() {
        return dataObjectExistence;
    }

    /**
     * Sets the value of the dataObjectExistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setDataObjectExistence(LevelConstraint value) {
        this.dataObjectExistence = value;
    }

    /**
     * Gets the value of the dataObjectIntact property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getDataObjectIntact() {
        return dataObjectIntact;
    }

    /**
     * Sets the value of the dataObjectIntact property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setDataObjectIntact(LevelConstraint value) {
        this.dataObjectIntact = value;
    }

    /**
     * Gets the value of the dataObjectFound property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getDataObjectFound() {
        return dataObjectFound;
    }

    /**
     * Sets the value of the dataObjectFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setDataObjectFound(LevelConstraint value) {
        this.dataObjectFound = value;
    }

    /**
     * Gets the value of the dataObjectGroup property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getDataObjectGroup() {
        return dataObjectGroup;
    }

    /**
     * Sets the value of the dataObjectGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setDataObjectGroup(LevelConstraint value) {
        this.dataObjectGroup = value;
    }

    /**
     * Gets the value of the cryptographic property.
     * 
     * @return
     *     possible object is
     *     {@link CryptographicConstraint }
     *     
     */
    public CryptographicConstraint getCryptographic() {
        return cryptographic;
    }

    /**
     * Sets the value of the cryptographic property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptographicConstraint }
     *     
     */
    public void setCryptographic(CryptographicConstraint value) {
        this.cryptographic = value;
    }

}
