//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:56:04 AM CET 
//


package eu.europa.esig.dss.policy.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Group of constraints on the unsigned attributes/properties
 * 
 * <p>Java class for UnsignedAttributesConstraints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnsignedAttributesConstraints"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CounterSignature" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="SignatureTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="ValidationDataTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="ValidationDataRefsOnlyTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="ArchiveTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="DocumentTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="TLevelTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *         &lt;element name="LTALevelTimeStamp" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnsignedAttributesConstraints", propOrder = {
    "counterSignature",
    "signatureTimeStamp",
    "validationDataTimeStamp",
    "validationDataRefsOnlyTimeStamp",
    "archiveTimeStamp",
    "documentTimeStamp",
    "tLevelTimeStamp",
    "ltaLevelTimeStamp"
})
public class UnsignedAttributesConstraints
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "CounterSignature")
    protected LevelConstraint counterSignature;
    @XmlElement(name = "SignatureTimeStamp")
    protected LevelConstraint signatureTimeStamp;
    @XmlElement(name = "ValidationDataTimeStamp")
    protected LevelConstraint validationDataTimeStamp;
    @XmlElement(name = "ValidationDataRefsOnlyTimeStamp")
    protected LevelConstraint validationDataRefsOnlyTimeStamp;
    @XmlElement(name = "ArchiveTimeStamp")
    protected LevelConstraint archiveTimeStamp;
    @XmlElement(name = "DocumentTimeStamp")
    protected LevelConstraint documentTimeStamp;
    @XmlElement(name = "TLevelTimeStamp")
    protected LevelConstraint tLevelTimeStamp;
    @XmlElement(name = "LTALevelTimeStamp")
    protected LevelConstraint ltaLevelTimeStamp;

    /**
     * Gets the value of the counterSignature property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getCounterSignature() {
        return counterSignature;
    }

    /**
     * Sets the value of the counterSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setCounterSignature(LevelConstraint value) {
        this.counterSignature = value;
    }

    /**
     * Gets the value of the signatureTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getSignatureTimeStamp() {
        return signatureTimeStamp;
    }

    /**
     * Sets the value of the signatureTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setSignatureTimeStamp(LevelConstraint value) {
        this.signatureTimeStamp = value;
    }

    /**
     * Gets the value of the validationDataTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getValidationDataTimeStamp() {
        return validationDataTimeStamp;
    }

    /**
     * Sets the value of the validationDataTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setValidationDataTimeStamp(LevelConstraint value) {
        this.validationDataTimeStamp = value;
    }

    /**
     * Gets the value of the validationDataRefsOnlyTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getValidationDataRefsOnlyTimeStamp() {
        return validationDataRefsOnlyTimeStamp;
    }

    /**
     * Sets the value of the validationDataRefsOnlyTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setValidationDataRefsOnlyTimeStamp(LevelConstraint value) {
        this.validationDataRefsOnlyTimeStamp = value;
    }

    /**
     * Gets the value of the archiveTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getArchiveTimeStamp() {
        return archiveTimeStamp;
    }

    /**
     * Sets the value of the archiveTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setArchiveTimeStamp(LevelConstraint value) {
        this.archiveTimeStamp = value;
    }

    /**
     * Gets the value of the documentTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getDocumentTimeStamp() {
        return documentTimeStamp;
    }

    /**
     * Sets the value of the documentTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setDocumentTimeStamp(LevelConstraint value) {
        this.documentTimeStamp = value;
    }

    /**
     * Gets the value of the tLevelTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getTLevelTimeStamp() {
        return tLevelTimeStamp;
    }

    /**
     * Sets the value of the tLevelTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setTLevelTimeStamp(LevelConstraint value) {
        this.tLevelTimeStamp = value;
    }

    /**
     * Gets the value of the ltaLevelTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getLTALevelTimeStamp() {
        return ltaLevelTimeStamp;
    }

    /**
     * Sets the value of the ltaLevelTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setLTALevelTimeStamp(LevelConstraint value) {
        this.ltaLevelTimeStamp = value;
    }

}
