//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:58:40 AM CET 
//


package eu.europa.esig.dss.pki.jaxb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.esig.dss.pki.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Pki_QNAME = new QName("http://pki-factory.nowina.lu/pki-factory", "pki");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.dss.pki.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlPki }
     * 
     */
    public XmlPki createXmlPki() {
        return new XmlPki();
    }

    /**
     * Create an instance of {@link XmlCertificateType }
     * 
     */
    public XmlCertificateType createXmlCertificateType() {
        return new XmlCertificateType();
    }

    /**
     * Create an instance of {@link XmlEmptyType }
     * 
     */
    public XmlEmptyType createXmlEmptyType() {
        return new XmlEmptyType();
    }

    /**
     * Create an instance of {@link XmlDateDefinitionType }
     * 
     */
    public XmlDateDefinitionType createXmlDateDefinitionType() {
        return new XmlDateDefinitionType();
    }

    /**
     * Create an instance of {@link XmlRevocationType }
     * 
     */
    public XmlRevocationType createXmlRevocationType() {
        return new XmlRevocationType();
    }

    /**
     * Create an instance of {@link XmlKeyAlgo }
     * 
     */
    public XmlKeyAlgo createXmlKeyAlgo() {
        return new XmlKeyAlgo();
    }

    /**
     * Create an instance of {@link XmlEntityKey }
     * 
     */
    public XmlEntityKey createXmlEntityKey() {
        return new XmlEntityKey();
    }

    /**
     * Create an instance of {@link XmlKeyUsages }
     * 
     */
    public XmlKeyUsages createXmlKeyUsages() {
        return new XmlKeyUsages();
    }

    /**
     * Create an instance of {@link XmlExtendedKeyUsages }
     * 
     */
    public XmlExtendedKeyUsages createXmlExtendedKeyUsages() {
        return new XmlExtendedKeyUsages();
    }

    /**
     * Create an instance of {@link XmlCertificatePolicies }
     * 
     */
    public XmlCertificatePolicies createXmlCertificatePolicies() {
        return new XmlCertificatePolicies();
    }

    /**
     * Create an instance of {@link XmlQcStatementIds }
     * 
     */
    public XmlQcStatementIds createXmlQcStatementIds() {
        return new XmlQcStatementIds();
    }

    /**
     * Create an instance of {@link XmlQcTypes }
     * 
     */
    public XmlQcTypes createXmlQcTypes() {
        return new XmlQcTypes();
    }

    /**
     * Create an instance of {@link XmlQcCClegislation }
     * 
     */
    public XmlQcCClegislation createXmlQcCClegislation() {
        return new XmlQcCClegislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlPki }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XmlPki }{@code >}
     */
    @XmlElementDecl(namespace = "http://pki-factory.nowina.lu/pki-factory", name = "pki")
    public JAXBElement<XmlPki> createPki(XmlPki value) {
        return new JAXBElement<XmlPki>(_Pki_QNAME, XmlPki.class, null, value);
    }

}
