//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:58:40 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://pki-factory.nowina.lu/pki-factory", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.europa.esig.dss.pki.jaxb;
