//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:58:40 AM CET 
//


package eu.europa.esig.dss.pki.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.europa.esig.dss.enumerations.DigestAlgorithm;


/**
 * Contains configuration of a single certificate token
 * 
 * <p>Java class for CertificateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pseudo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="issuer" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey"/&gt;
 *         &lt;element name="crossCertificate" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey" minOccurs="0"/&gt;
 *         &lt;element name="ocspResponder" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey" minOccurs="0"/&gt;
 *         &lt;element name="notBefore" type="{http://pki-factory.nowina.lu/pki-factory}DateDefinitionType"/&gt;
 *         &lt;element name="notAfter" type="{http://pki-factory.nowina.lu/pki-factory}DateDefinitionType"/&gt;
 *         &lt;element name="keyAlgo" type="{http://pki-factory.nowina.lu/pki-factory}KeyAlgo"/&gt;
 *         &lt;element name="digestAlgo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="keyUsages" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="keyUsage" type="{http://pki-factory.nowina.lu/pki-factory}KeyUsageBit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="extendedKeyUsages" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="extendedKeyUsage" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="certificatePolicies" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="certificatePolicy" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ca" type="{http://pki-factory.nowina.lu/pki-factory}emptyType" minOccurs="0"/&gt;
 *         &lt;element name="ocspNoCheck" type="{http://pki-factory.nowina.lu/pki-factory}emptyType" minOccurs="0"/&gt;
 *         &lt;element name="qcStatementIds" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="qcStatement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="qcTypes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="qcType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="qcCClegislation" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="crl" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey" minOccurs="0"/&gt;
 *         &lt;element name="ocsp" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey" minOccurs="0"/&gt;
 *         &lt;element name="caIssuers" type="{http://pki-factory.nowina.lu/pki-factory}EntityKey" minOccurs="0"/&gt;
 *         &lt;element name="trustAnchor" type="{http://pki-factory.nowina.lu/pki-factory}emptyType" minOccurs="0"/&gt;
 *         &lt;element name="revocation" type="{http://pki-factory.nowina.lu/pki-factory}RevocationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateType", propOrder = {
    "serialNumber",
    "subject",
    "organization",
    "country",
    "pseudo",
    "issuer",
    "crossCertificate",
    "ocspResponder",
    "notBefore",
    "notAfter",
    "keyAlgo",
    "digestAlgo",
    "keyUsages",
    "extendedKeyUsages",
    "certificatePolicies",
    "ca",
    "ocspNoCheck",
    "qcStatementIds",
    "qcTypes",
    "qcCClegislation",
    "crl",
    "ocsp",
    "caIssuers",
    "trustAnchor",
    "revocation"
})
public class XmlCertificateType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    protected long serialNumber;
    @XmlElement(required = true)
    protected String subject;
    protected String organization;
    protected String country;
    protected String pseudo;
    @XmlElement(required = true)
    protected XmlEntityKey issuer;
    protected XmlEntityKey crossCertificate;
    protected XmlEntityKey ocspResponder;
    @XmlElement(required = true)
    protected XmlDateDefinitionType notBefore;
    @XmlElement(required = true)
    protected XmlDateDefinitionType notAfter;
    @XmlElement(required = true)
    protected XmlKeyAlgo keyAlgo;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter5 .class)
    protected DigestAlgorithm digestAlgo;
    protected XmlKeyUsages keyUsages;
    protected XmlExtendedKeyUsages extendedKeyUsages;
    protected XmlCertificatePolicies certificatePolicies;
    protected XmlEmptyType ca;
    protected XmlEmptyType ocspNoCheck;
    protected XmlQcStatementIds qcStatementIds;
    protected XmlQcTypes qcTypes;
    protected XmlQcCClegislation qcCClegislation;
    protected XmlEntityKey crl;
    protected XmlEntityKey ocsp;
    protected XmlEntityKey caIssuers;
    protected XmlEmptyType trustAnchor;
    protected XmlRevocationType revocation;

    /**
     * Gets the value of the serialNumber property.
     * 
     */
    public long getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     */
    public void setSerialNumber(long value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the pseudo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPseudo() {
        return pseudo;
    }

    /**
     * Sets the value of the pseudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPseudo(String value) {
        this.pseudo = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setIssuer(XmlEntityKey value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the crossCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getCrossCertificate() {
        return crossCertificate;
    }

    /**
     * Sets the value of the crossCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setCrossCertificate(XmlEntityKey value) {
        this.crossCertificate = value;
    }

    /**
     * Gets the value of the ocspResponder property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getOcspResponder() {
        return ocspResponder;
    }

    /**
     * Sets the value of the ocspResponder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setOcspResponder(XmlEntityKey value) {
        this.ocspResponder = value;
    }

    /**
     * Gets the value of the notBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDateDefinitionType }
     *     
     */
    public XmlDateDefinitionType getNotBefore() {
        return notBefore;
    }

    /**
     * Sets the value of the notBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDateDefinitionType }
     *     
     */
    public void setNotBefore(XmlDateDefinitionType value) {
        this.notBefore = value;
    }

    /**
     * Gets the value of the notAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDateDefinitionType }
     *     
     */
    public XmlDateDefinitionType getNotAfter() {
        return notAfter;
    }

    /**
     * Sets the value of the notAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDateDefinitionType }
     *     
     */
    public void setNotAfter(XmlDateDefinitionType value) {
        this.notAfter = value;
    }

    /**
     * Gets the value of the keyAlgo property.
     * 
     * @return
     *     possible object is
     *     {@link XmlKeyAlgo }
     *     
     */
    public XmlKeyAlgo getKeyAlgo() {
        return keyAlgo;
    }

    /**
     * Sets the value of the keyAlgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlKeyAlgo }
     *     
     */
    public void setKeyAlgo(XmlKeyAlgo value) {
        this.keyAlgo = value;
    }

    /**
     * Gets the value of the digestAlgo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DigestAlgorithm getDigestAlgo() {
        return digestAlgo;
    }

    /**
     * Sets the value of the digestAlgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestAlgo(DigestAlgorithm value) {
        this.digestAlgo = value;
    }

    /**
     * Gets the value of the keyUsages property.
     * 
     * @return
     *     possible object is
     *     {@link XmlKeyUsages }
     *     
     */
    public XmlKeyUsages getKeyUsages() {
        return keyUsages;
    }

    /**
     * Sets the value of the keyUsages property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlKeyUsages }
     *     
     */
    public void setKeyUsages(XmlKeyUsages value) {
        this.keyUsages = value;
    }

    /**
     * Gets the value of the extendedKeyUsages property.
     * 
     * @return
     *     possible object is
     *     {@link XmlExtendedKeyUsages }
     *     
     */
    public XmlExtendedKeyUsages getExtendedKeyUsages() {
        return extendedKeyUsages;
    }

    /**
     * Sets the value of the extendedKeyUsages property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlExtendedKeyUsages }
     *     
     */
    public void setExtendedKeyUsages(XmlExtendedKeyUsages value) {
        this.extendedKeyUsages = value;
    }

    /**
     * Gets the value of the certificatePolicies property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCertificatePolicies }
     *     
     */
    public XmlCertificatePolicies getCertificatePolicies() {
        return certificatePolicies;
    }

    /**
     * Sets the value of the certificatePolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCertificatePolicies }
     *     
     */
    public void setCertificatePolicies(XmlCertificatePolicies value) {
        this.certificatePolicies = value;
    }

    /**
     * Gets the value of the ca property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEmptyType }
     *     
     */
    public XmlEmptyType getCa() {
        return ca;
    }

    /**
     * Sets the value of the ca property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEmptyType }
     *     
     */
    public void setCa(XmlEmptyType value) {
        this.ca = value;
    }

    /**
     * Gets the value of the ocspNoCheck property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEmptyType }
     *     
     */
    public XmlEmptyType getOcspNoCheck() {
        return ocspNoCheck;
    }

    /**
     * Sets the value of the ocspNoCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEmptyType }
     *     
     */
    public void setOcspNoCheck(XmlEmptyType value) {
        this.ocspNoCheck = value;
    }

    /**
     * Gets the value of the qcStatementIds property.
     * 
     * @return
     *     possible object is
     *     {@link XmlQcStatementIds }
     *     
     */
    public XmlQcStatementIds getQcStatementIds() {
        return qcStatementIds;
    }

    /**
     * Sets the value of the qcStatementIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlQcStatementIds }
     *     
     */
    public void setQcStatementIds(XmlQcStatementIds value) {
        this.qcStatementIds = value;
    }

    /**
     * Gets the value of the qcTypes property.
     * 
     * @return
     *     possible object is
     *     {@link XmlQcTypes }
     *     
     */
    public XmlQcTypes getQcTypes() {
        return qcTypes;
    }

    /**
     * Sets the value of the qcTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlQcTypes }
     *     
     */
    public void setQcTypes(XmlQcTypes value) {
        this.qcTypes = value;
    }

    /**
     * Gets the value of the qcCClegislation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlQcCClegislation }
     *     
     */
    public XmlQcCClegislation getQcCClegislation() {
        return qcCClegislation;
    }

    /**
     * Sets the value of the qcCClegislation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlQcCClegislation }
     *     
     */
    public void setQcCClegislation(XmlQcCClegislation value) {
        this.qcCClegislation = value;
    }

    /**
     * Gets the value of the crl property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getCrl() {
        return crl;
    }

    /**
     * Sets the value of the crl property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setCrl(XmlEntityKey value) {
        this.crl = value;
    }

    /**
     * Gets the value of the ocsp property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getOcsp() {
        return ocsp;
    }

    /**
     * Sets the value of the ocsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setOcsp(XmlEntityKey value) {
        this.ocsp = value;
    }

    /**
     * Gets the value of the caIssuers property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEntityKey }
     *     
     */
    public XmlEntityKey getCaIssuers() {
        return caIssuers;
    }

    /**
     * Sets the value of the caIssuers property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEntityKey }
     *     
     */
    public void setCaIssuers(XmlEntityKey value) {
        this.caIssuers = value;
    }

    /**
     * Gets the value of the trustAnchor property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEmptyType }
     *     
     */
    public XmlEmptyType getTrustAnchor() {
        return trustAnchor;
    }

    /**
     * Sets the value of the trustAnchor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEmptyType }
     *     
     */
    public void setTrustAnchor(XmlEmptyType value) {
        this.trustAnchor = value;
    }

    /**
     * Gets the value of the revocation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlRevocationType }
     *     
     */
    public XmlRevocationType getRevocation() {
        return revocation;
    }

    /**
     * Sets the value of the revocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlRevocationType }
     *     
     */
    public void setRevocation(XmlRevocationType value) {
        this.revocation = value;
    }

}
