//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 08:58:40 AM CET 
//


package eu.europa.esig.dss.pki.jaxb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.europa.esig.dss.enumerations.RevocationReason;


/**
 * Contains revocation status information for a revoked certificate.
 * 
 * <p>Java class for RevocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevocationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pki-factory.nowina.lu/pki-factory}DateDefinitionType"&gt;
 *       &lt;attribute name="reason" type="{http://pki-factory.nowina.lu/pki-factory}RevocationReason" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevocationType")
public class XmlRevocationType
    extends XmlDateDefinitionType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    @XmlAttribute(name = "reason")
    @XmlJavaTypeAdapter(Adapter3 .class)
    protected RevocationReason reason;

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public RevocationReason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(RevocationReason value) {
        this.reason = value;
    }

}
